apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
data:
  homeserver.yaml: |-
{{ .Files.Get "envfiles/homeserver.yaml" | indent 4 }}
  mongo-dao.ts: |-
{{ .Files.Get "envfiles/mongo-dao.ts" | indent 4 }}