apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
data:
  config.local.ts: |-
{{ .Files.Get "envfiles/config.local.js" | indent 4 }}
  config.test.ts: |-
{{ .Files.Get "envfiles/config.test.js" | indent 4 }}